### ISSUE TITLE
Spacy nlp.from_bytes fails to load thinc vectors

### ISSUE THREAD

**Issue by smiles3983** [explosion/thinc#113]
When loading the Spacy English large model using the nlp.from_bytes method, it appears that thinc underneath is still trying to find the en_model.vectors from the disk.  I have a storage constraint, and am loading the entire model from S3 in binary.  It worked in version 2.0.0 of the model but version 2.1.0 now has the en_model.vectors meta.  

https://github.com/explosion/thinc/blob/ab24ef3c0418b3ce547cd75e9db1f3487250626b/thinc/extra/load_nlp.py#L14

https://github.com/explosion/spaCy/issues/4250

**Comment by svlandeg** [comment]
I guess this got addressed in https://github.com/explosion/spaCy/issues/4250 and should be resolved in 2.2 ?
