### ISSUE TITLE
Random bytes test failure in windows

### ISSUE THREAD

**Issue by rolando** [explosion/thinc#22]
I'm building conda packages for `thinc` and windows builds fail since `0.6.3` when testing `thinc.neural.ops.NumpyOps.random_bytes`.

I debugged around and found out that it doesn't return random bytes at all.

```
================================== FAILURES ===================================
______________________________ test_random_bytes ______________________________
ops = <thinc.neural.ops.NumpyOps object at 0x000000496CDF3F60>
    def test_random_bytes(ops):
        n = 10
        byte_str = ops.random_bytes(n)
        assert len(byte_str) == n
>       assert byte_str != ops.random_bytes(n)
E       AssertionError: assert b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' != b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
E        +  where b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' = <bound method NumpyOps.random_bytes of <thinc.neural.ops.NumpyOps object at 0x000000496CDF3F60>>(10)
E        +    where <bound method NumpyOps.random_bytes of <thinc.neural.ops.NumpyOps object at 0x000000496CDF3F60>> = <thinc.neural.ops.NumpyOps object at 0x000000496CDF3F60>.random_bytes
..\_t_env\lib\site-packages\thinc\tests\unit\test_ops.py:62: AssertionError
========= 1 failed, 657 passed, 13 skipped, 6 xfailed in 7.31 seconds =========
```

This for Python 2.7 (vc9) and 3.5 (vc14). See the Appveyor build: https://ci.appveyor.com/project/rolando/staged-recipes/build/1.0.185/job/8a5up7hillrabm66

If I change the method to return `numpy.random.bytes(n)` (and re-cythonize) then it passes the tests.

**Comment by honnibal** [comment]
Thanks!

This method should simply be deleted --- it was an experiment that should never have made it to master. It shouldn't be used anywhere.

**Comment by honnibal** [comment]
Just getting a release ready for this, and then getting a release ready for spaCy. This will give you the tags you need to do the conda builds. Thanks again for your help!

**Comment by rolando** [comment]
Great!

Rolando

**Comment by honnibal** [comment]
Both should be up now.
