### ISSUE TITLE
Consider using monads for better composition

### ISSUE THREAD

**Issue by sobolevn** [explosion/thinc#292]
I am very exited to see more functional and typed tools in Python! Thanks a lot for building it!

I am one of the core developers of `dry-python` project and [`returns`](https://github.com/dry-python/returns) library. We build typed python monads.

We have:

- `Maybe` (or `Option`) monad for working with `None` and `Optional[]` values
- `Result` (or `Either`) to work with functions that might throw errors
- `IO` to explicitly mark impure operations
- `RequiresContext` (or `Reader`) to provide functional typed dependency injection and context related tasks

Transformations, composition utilities, and some combinators like `IOResult`, `RequiresContextResult`, `RequiresContextIOResult` and other tools.

I guess it might be helpful for this project, because you already use a lot of functional stuff. What do you think? 

Repo: https://github.com/dry-python/returns
Docs: https://returns.readthedocs.io/en/latest/

**Comment by honnibal** [comment]
Hey, thanks for the pointer to the library!

I think there's interesting stuff there and I'd find it cool to explore some of these aspects of functional programming more deeply. But for Thinc we'd like to have the mechanisms be a bit more transparent, and so I don't think we'll be taking this approach --- it's likely to make the code less accessible to a lot of developers.
