### ISSUE TITLE
Issue in Embed

### ISSUE THREAD

**Issue by naveenjafer** [explosion/thinc#306]
@honnibal 
I have a model as below using HashEmbed, which trains without any issues.
```
with Model.define_operators({">>": chain}):
    model = (
        strings2arrays() 
        >> list2padded() 
        >> with_array(HashEmbed(nO=width, nV=10, column=0))
        >> LSTM(nO=100, nI=width)        
        >> with_array(Softmax(nO=n_tags+1, nI=100))
        >> padded2list()
    )
```

When I replace HashEmbed with Embed, I run into some error like "IndexError: index 94100425 is out of bounds for axis 0 with size 11". The error is thrown in  
`---> 55     output = vectors[ids]` of /thinc/layers/embed.py  

I tried comparing the code of HashEmbed to Embed to understand what might be causing this issue, but I had no luck. I even updated HashEmbed to calculate output as  
`output = vectors[ids]  `
instead of 
`output = vectors[keys].sum(axis=1)`
to try and reproduce the error in HashEmbed, but it works just the same.

I also have a doubt regarding the nV input. I believe nO is the embedding dimension, but then what is nV? In the case of Embed it defaults to 1 and not in the case of HashEmbed.

**Comment by naveenjafer** [comment]
I think I figured the issue, it seems to be a bug with how Embed is implemented. In the forward method of embed.py modding ids by nV ensures that they are all in range. This is similar to something that is done with the hashembed.py method. I will put in a pull req for this if that's okay.

```
ids = ids % nV
output = vectors[ids]
```

@honnibal And as for my previous question, I guess nV technically should be set to the number of unique words in the vocab?  

I also have a doubt regards this 'ids' array. This is a sample of the numbers in it  
```
[            94100425 18446744072411621407           1558403699
 18446744073360372835            603615019            131900689
 18446744072992786556 18446744072281243677 18446744072757647121
           1299665196 18446744072576802658 18446744073308518867
 18446744073252088270            589538811 18446744072576802658
            979103863 18446744072576802658 18446744071958240053
 18446744071931561673 18446744073272641596           2021799277
 18446744073253355074           1832516214 18446744072608696245
 18446744073259610218 18446744072459575127           1299665196
           1299665196 18446744071958240053 18446744071646439289
            893251777 18446744072576802658           1009084850
``` 
I guess these numbers are created during the strings2array step? But why is the range of numbers so large?. I would have expected the numbers in ids to be <= number of words in my vocab.

**Comment by honnibal** [comment]
I think this should be fixed now, cleaning out old issues.
