### ISSUE TITLE
Multi Input

### ISSUE THREAD

**Issue by cosmincatalin** [explosion/thinc#307]
Can thinc be used for multi input training of models?

As in
```
model.begin_update(X1, X2, X3)
```

**Comment by svlandeg** [comment]
`model.begin_update()` only supports one argument `X`, which is a batch of input data. The type and shape of `X` is important because shapes of the internal weights etc will depend on it.

What would be your use-case for adding multiple inputs, and how would you expect that to work?

**Comment by honnibal** [comment]
The solution would be to pass in a tuple, like `model.begin_update((X1, X2, X3))`. I would recommend making a small dataclass though, to make it easier to work with the input type more explicitly. This also makes the type declarations really easy. You might find the `thinc.types.Pairs` dataclass a helpful reference: https://github.com/explosion/thinc/blob/master/thinc/types.py#L880

**Comment by cosmincatalin** [comment]
A use case would be if I had two separate networks being concatenated, one processes an image and the other a vector. In MXNet's Gluon I could do something like `net(X1, X2, X3)`. Where the X1, X2 and X3 have different shapes.

**Comment by reesehopkins** [comment]
Here's an example. I can't find a way to pass X1 and X2 to the `model.initialize` or `model.begin_update` without an error.

```python
from thinc.api import Linear, zero_init, concatenate, chain
import numpy

X1 = numpy.zeros((128, 20), dtype="f")
X2 = numpy.zeros((128, 12), dtype="f")
Y = numpy.zeros((128, 10), dtype="f")
layer_1a = Linear(nI=X1.shape[1], nO=10, init_W=zero_init)
layer_1b = Linear(nI=X2.shape[1], nO=6, init_W=zero_init)
layer_2 = Linear(nI=16, nO=Y.shape[1], init_W=zero_init)
model = chain(concatenate(layer_1a, layer_1b), layer_2)
```
