### ISSUE TITLE
cython pinning prevents installation on PyPy

### ISSUE THREAD

**Issue by mattip** [explosion/thinc#31]
cython is pinned to version <0.24 in requirements.txt. PyPy cannot install with that version, it needs the latest which is 0.25.2. Is the pinning required?

**Comment by mattip** [comment]
(note that that only get me to the next problem, which is a failure in ``cytoolz`` on PyPy)

**Comment by mattip** [comment]
some kind soul pointed me to the environmental markers syntax of pip, so starting in pip 6.0 this might work
```
cytoolz; python_implementation == "cpython"
toolz; python_implementation == "pypy"
```
Can you assume pip 6.0 and up, should I make a pull request?

**Comment by honnibal** [comment]
Sorry for missing this before.

When was pip 6 released, and what will happen if people try to install with pip < 6?

I think you might be on error 2/674 here. A lot of the library is written in Cython, with fairly low level code. My understanding is that this tends to not work very well on PyPy?

You might want to check whether my dependent libraries cymem and preshed work on PyPy. These are much smaller, and if they can't be made to work on PyPy, there's really no chance thinc ever will.

**Comment by mattip** [comment]
Not sure what "on error 2/674 here" means. pip 6 was released [22 Dec 2014](https://github.com/pypa/pip/releases?after=6.0.7). This all started as a stackoverflow question about [Spacy](https://stackoverflow.com/questions/44492591), I can ``pip install cymem preshed``, and they pass the minimal tests they ship with. I cannot build thinc, on both CPython and PyPy running ``python setup.py build_ext -i`` fails to cythonize ``ops.pyx`` with:   
```
Processing thinc/neural/ops.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from libc.math cimport exp, sqrt, isnan
from libc.stdlib cimport srand, rand
from libc.stdlib cimport calloc, malloc, free
from libc.stdint cimport uint32_t, uint64_t
from libc.string cimport memcpy
from cymem.cymem cimport Pool
^
------------------------------------------------------------

ops.pyx:11:0: 'cymem/cymem.pxd' not found

```

**Comment by honnibal** [comment]
By "on error 2/674", I meant that I suspect you're seeing the first cosmetic problems of what might be a much deeper incompatibility --- I meant that you've gotten past the first error, and there might now be 673 more to solve.

The `cymem` error you see there means that the header file that ships with `cymem` isn't being read accessed correctly. Thinc access `cymem` through its C API, so it needs the .pxd declarations. This might be not supported in PyPy, or it might just be a configuration issue.

**Comment by honnibal** [comment]
I take it all back -- just tried the new PyPy release, and Thinc is working fine on Cython 0.27.1 and PyPy. I'll fix the version pin.

spaCy still has some problems, but Cymem, Preshed and Murmurhash are all working --- so getting spaCy working on PyPy seems very feasible.

**Comment by mattip** [comment]
Cool. Feel free to ping me if there is something needed to  get SpaCy issues resolved
