### ISSUE TITLE
Example in thinc documentation for Linear layer 

### ISSUE THREAD

**Issue by naveenjafer** [explosion/thinc#318]
The documentation for the Linear layer does not seem to be working as expected. https://thinc.ai/docs/api-layers#linear . I dont think "allocate" exists anymore, hence I used 
```
from thinc.api import Linear

model = Linear(10, 5)
Y = model.predict(model.ops.alloc2f(2, 5))
assert Y.shape == (2, 10)
```
But this is the error it throws  
`KeyError: "Parameter 'W' for model 'linear' has not been allocated yet."
`
Am I missing something?

**Comment by svlandeg** [comment]
Thanks for the report! You'll have to call `model.initialize()` to make this work. I will update the documentation.

```
model = Linear(10, 5)
model.initialize()
Y = model.predict(model.ops.alloc2f(2, 5))
assert Y.shape == (2, 10)
```
