### ISSUE TITLE
Use of 'nonlocal' keyword breaks Python2 compatibility

### ISSUE THREAD

**Issue by Ed-von-Schleck** [explosion/thinc#32]
Usage of thinc (and therefore, spaCy) is currently not possible on Python2 because the `nonlocal` keyword is used twice:

```bash
$ git grep nonlocal
thinc/neural/_classes/rnn.py:            nonlocal Zs, d_pad, dWx, dWh, db
thinc/neural/_classes/rnn.py:            nonlocal dW, db
```

If I got it right, these changes were introduced with commits 58f7c157cb592539bca8b71e640b1a30a2eda57a and 456177aba82abac6ab7df2c62454e5ef8a55c035 from  2017-06-18 and 2017-06-21, respectively.

I can provide a patch if a preferred workaround is suggested.

**Comment by honnibal** [comment]
The `rnn` module should be switched over to develop for now -- I shouldn't have pushed this to master.

Is this really breaking spaCy already though? I didn't think this module was being imported by anything, so I didn't think it would matter.

**Comment by Ed-von-Schleck** [comment]
We use debian-packages for deployment, where `.py`-files get pre-compiled on installation (AFAIK that's not unusual – the rpm-toolchain does the same). There I get

```
Compiling /usr/lib/pymodules/python2.7/thinc/neural/_classes/rnn.py ...
  File "/usr/lib/pymodules/python2.7/thinc/neural/_classes/rnn.py", line 213
    nonlocal Zs, d_pad, dWx, dWh, db
              ^
SyntaxError: invalid syntax
```

**Comment by honnibal** [comment]
Fixed. Sorry for the delay.
