### ISSUE TITLE
[Help][Not a Bug] Development toolchain guidance

### ISSUE THREAD

**Issue by naveenjafer** [explosion/thinc#320]
@adrianeboyd @honnibal What's the best/most efficient way to go about with functionally testing changes made to the thinc code base. Currently, this is the process I use.  

1. python setup.py build_ext --inplace  
2. python setup.py install  
3. Restart jupyter server
4. Run my notebook cells afresh. 

I feel this becomes a little troublesome for beginners such as me who test out code very frequently. Would like to know if you have any better suggestions.

**Comment by svlandeg** [comment]
It might be a bit of a burden indeed to restart jupyter every time you recompiled. I think none of us really work with Jupyter on a daily basis. Personally I just have two screens next to eachother: one holding the console where I recompile the code when need be, and the other holding a Python IDE such as PyCharm where I execute my scripts.
