### ISSUE TITLE
[Not a bug] Modifying model.ops function for Relu

### ISSUE THREAD

**Issue by naveenjafer** [explosion/thinc#321]
Hi, I was playing around with the Relu implementation. I needed to modify the model.ops.relu function by adding a new input param for a use case, I did that and built using  
```
python setup.py build_ext --inplace
python setup.py install  
```
However, i run into an error telling 
```
scratch/thinc_fork/thinc/thinc/backends/numpy_ops.pyx in thinc.backends.numpy_ops.NumpyOps.relu()

TypeError: relu() got an unexpected keyword argument 'alphaLeaky'
```
I see that the numpy_ops.pyx file still has the old version of relu. I assumed that the numpy_ops.pyx file is generated from the .py? If yes, what am I doing wrong that it doesnt reflect the changes from ops.py. 

TIA.

**Comment by svlandeg** [comment]
If you modify `numpy_ops.pyx` and recompile, a corresponding `.pyd` and `.cpp` file will be built. 

I'll assume you were editing the Class `Ops` in `ops.py` ? There are several inheriting classes: `NumpyOps`, `CupyOps` and `JaxOps`, so you'll have to change their signature accordingly.
