### ISSUE TITLE
examples\transformers_tagger TypeError: can only concatenate str

### ISSUE THREAD

**Issue by GoooIce** [explosion/thinc#328]
run **examples\transformers_tagger.py** 

got this:
```
    nb_tag = max(max(y) for y in train_y) + 1
TypeError: can only concatenate str (not "int") to str
```
https://github.com/explosion/ml-datasets/blob/2ec21d174139c69350f80a2d4d8085ce6b49c90c/ml_datasets/universal_dependencies.py#L68

> win10
> python3.7.3

**Comment by svlandeg** [comment]
Hi @GoooIce , curious to know why you closed this again? Was it not a bug in the code ?

**Comment by GoooIce** [comment]
yeah, was not a bug. so i closed @svlandeg

**Comment by svlandeg** [comment]
Ok, cool, thanks for letting us know and happy to hear you figured it out! ;-)
