### ISSUE TITLE
Compile options for msvc are malformed

### ISSUE THREAD

**Issue by timkpaine** [explosion/thinc#33]
Looks like the compile options for msvc are malformed in setup.py, MSVC shoudnt map to a dictionary. Let me know if you want me to PR

**Comment by honnibal** [comment]
Sure! I haven't been able to debug on Windows yet. If you can get it working with NVCC as well that would be especially useful.

**Comment by honnibal** [comment]
Got appveyor running, allowing me to reproduce the error. Should be fixed now. Should have better Windows support going forward, too!
