### ISSUE TITLE
Does imdb_lstm.py use an LSTM?

### ISSUE THREAD

**Issue by jnothman** [explosion/thinc#35]
https://github.com/explosion/thinc/blob/master/examples/imdb_lstm.py seems to use convolution and not LSTM, despite the name...

**Comment by honnibal** [comment]
Now renamed, thanks. The examples are currently rather messy unfortunately.

**Comment by jnothman** [comment]
make a gallery of them so they are more visible, so that users contribute
to their maintenance, and so that they are run by CI...
