### ISSUE TITLE
Potential dependency conflicts between thinc and cymem

### ISSUE THREAD

**Issue by NeolithEra** [explosion/thinc#351]
Hi, as shown in the following full dependency graph of **_thinc_**, **_thinc_** requires **_cymem <2.1.0,>=2.0.2_**, **_thinc_** requires **_preshed <3.1.0,>=1.0.1_** (**_preshed 3.0.2_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_preshed 3.0.2_** transitively introduces **_cymem <2.1.0,>=2.0.2_**.

Obviously, there are multiple version constraints set for **_cymem_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_cymem 2.0.3_** (i.e., the newest version satisfying constraint **_<2.1.0,>=2.0.2_**) is the actually installed version.

Although the first found package version **_cymem 2.0.3_** just satisfies the later dependency constraint （**_cymem <2.1.0,>=2.0.2_**), such installed version is very close to the upper bound of the version constraint of cymem specified by **_preshed 3.0.2_**. 

Once **_preshed_** upgrades，its newest version will be installed, as **_thinc_** does not specify the upper bound of version constraint for **_preshed_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_preshed_** version introduces a higher version of **_cymem_**, violating its another version constraint **_<2.1.0,>=2.0.2_**.

According to the release history of preshed, it habitually upgrates Cymem in its recent releases. For instance, preshed 2.0.0 upgrated Cymem’s constraint from **_>=2.0.1,<2.1.0 to >=2.0.0,<2.1.0_**,preshed 2.0.1 upgrated Cymem’s constraint from **_>=2.0.0,<2.1.0 to >=2.0.1,<2.1.0_** and preshed 2.0.2 upgrated Cymem’s constraint from **_>=2.0.1,<2.1.0 to >=2.0.2,<2.1.0_**. 

As such, it is a warm warning of a potential dependency conflict issue for thinc.

### Dependency tree
```
thinc - 7.4.1
| +- blis(install version:0.4.1 version range:<0.5.0,>=0.4.0)
| +- catalogue(install version:1.0.0 version range:<1.1.0,>=0.0.7)
| +- cymem(install version:2.0.3 version range:<2.1.0,>=2.0.2)
| +- murmurhash(install version:1.0.2 version range:<1.1.0,>=0.28.0)
| +- numpy(install version:1.18.2 version range:>=1.7.0)
| +- pathlib(install version:1.0.1 version range:==1.0.1)
| +- plac(install version:1.1.3 version range:<1.2.0,>=0.9.6)
| +- preshed(install version:3.0.2 version range:<3.1.0,>=1.0.1)
| | +- cymem(install version:2.0.3 version range:<2.1.0,>=2.0.2)
| | +- murmurhash(install version:1.0.2 version range:>=0.28.0,<1.1.0)
| +- srsly(install version:1.0.2 version range:<1.1.0,>=0.0.6)
| | +- pathlib(install version:1.0.1 version range:==1.0.1)
| +- tqdm(install version:4.46.0 version range:<5.0.0,>=4.10.0)
| +- wasabi(install version:0.6.0 version range:<1.1.0,>=0.0.9)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_cymem_** to be **_>=2.0.3_**.
2.	Remove your direct dependency **_cymem_**, and use the **_cymem_** transitively introduced by **_preshed_**.
3.	Change your direct dependency **_preshed_** to be **_>=1.0.1,<=3.0.2_**.
@honnibal  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by svlandeg** [comment]
Just to clarify, there currently isn't any conflict with the different dependencies, right? It looks like they're currently properly aligned. But you're opening this issue because there could be potential conflicts in the future?

Not sure we can always avoid that. I guess in this case we could go for option 2 and rely on the indirect requirement. But in general we often have these requirements that need to be aligned across packages and releases, as some installations are optional (e.g. spacy-transformers). I think we do try to make sure they stay aligned.
