### ISSUE TITLE
building thinc fails

### ISSUE THREAD

**Issue by RaananHadar** [explosion/thinc#39]
Hi,
I am trying to install spacy-nightly.

Building the latest version of thinc fails on:
`nvcc fatal   : Value 'sm_20' is not defined for option 'gpu-architecture'
`
I am using cuda 9.0 and indeed its not supporting sm_20. 
Trying to downgrade to cuda 8.0 adds back support for sm_20 but fails because it requires gcc with version smaller than 5. Any way on making this work without all this version hell?

any ideas on how to solve this? maybe there is something to change in the make file?

A docker image is also a viable option. thank you.

**Comment by honnibal** [comment]
If you have a look in `setup.py`, you should find the logic that sets those compiler flags. I don't have a CUDA 9 machine to test against, but I'd love a pull request that fixes this if you have time?

Thank for reporting.

**Comment by honnibal** [comment]
Added a workaround: if you set `CUDA9=1`, it should remove the compiler flag. What we need is a way to detect the CUDA version, so this becomes unnecessary.

**Comment by RaananHadar** [comment]
@honnibal thank you. I've tried the latest build but it seems cuda 9 no longer supports sm-20. I've created a pull request with the ommited flag and the build succeeds on my system.

Please note that my goal is to ultimately install spacy-nightly. When I do 'pip install spacy-nightly' it seems to uninstall my built thinc and attempt to install the old version unsuccessfully. Is there anything I can do?

Thanks.

**Comment by honnibal** [comment]
@RaananHadar We'll be pushing a new spaCy release pretty soon.

**Comment by RaananHadar** [comment]
Thank you!
