### ISSUE TITLE
Export Thinc model to ONNX format

### ISSUE THREAD

**Issue by Lap1n** [explosion/thinc#401]
Hi,

I am wondering if it is (or would be) possible to export the model to ONNX format so we can leverage the use of model optimization tools (like TensorRT).

**Comment by honnibal** [comment]
The best solution for that will be to use a shim around the ONNX model. This will let you run the model with TensorRT, and then only call into it from Python. I think you'll be able to use the existing PyTorch wrapping layers for this. So basically the onion will go: Thinc wrapping PyTorch, which wraps TensorRT. Does that make sense?

**Comment by Lap1n** [comment]
If I understood correctly, lets say that I have the following model  : 
```python
model = chain(
    PyTorchWrapper(torch.nn.Linear(16, 8)),
    Linear(4, 8)
)
```
I can export the Pytorch part of the model to ONNX, but I cannot export the full model to the ONNX format (with Thinc's Linear layer).  Is that correct?

**Comment by svlandeg** [comment]
Yep seems correct to me.
