### ISSUE TITLE
Config system as a separate package

### ISSUE THREAD

**Issue by jklaise** [explosion/thinc#408]
I feel like the config system together with the function registry is a killer feature of Thinc, so much so that I can see it as a standalone solution to solve all kinds of configuration problems in Python. Would there be any interest in making it installable as a standalone package? I understand this may be a cheeky question as there are some costs associated with decoupling and maintaining yet another package, but I wanted to ask anyway!

**Comment by bdewilde** [comment]
FWIW: A few months back I used `catalogue` along with a home-brewed config system inspired by `thinc`'s to define multi-component ML pipelines -- and put them to use in production. There's definitely a use case! Especially for folks who don't need or aren't ready to commit to a full-featured framework like, say, MLflow.

**Comment by hbredin** [comment]
I'd also use (and beta test) such a separate config/registry package! 

In the meantime, I might still consider adding `thinc` as a dependency to my current project just for `thinc.Config` and `thinc.registry`.

**Comment by svlandeg** [comment]
Yes, I think the plan is to move this functionality in `catalogue` indeed :-)

**Comment by mr-bjerre** [comment]
Is there an overview of the necessary steps? I'd like to help if possible

**Comment by svlandeg** [comment]
As an update, this is now work in progress. We've already started moving things to `catalogue`: https://github.com/explosion/catalogue/pull/33

The remaining steps will be mainly technical (coordinating releases & versioning) but we hope to finalize this soonish.

**Comment by rmitsch** [comment]
The config system is now included in [`catalogue`](https://github.com/explosion/catalogue).

**Comment by rmitsch** [comment]
Correction: integrating the config system in `catalogue` causes some issues with other dependencies. For the time being the config functionality will still be included in Thinc, but we are working on moving this to a separate package.

**Comment by rmitsch** [comment]
The config system is now available as a standalone package: [`confection`](https://github.com/explosion/confection).
