### ISSUE TITLE
compiling fails on cuda 9.0 ("Failed building wheel for thinc")

### ISSUE THREAD

**Issue by christophfink** [explosion/thinc#42]
Compilation (also via pip) fails on Arch Linux with CUDA 9.0.176

error message is: `nvcc fatal   : Value 'sm_20' is not defined for option 'gpu-architecture'`

    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2017 NVIDIA Corporation
    Built on Fri_Sep__1_21:08:03_CDT_2017
    Cuda compilation tools, release 9.0, V9.0.176

It seems that `sm_20` is no longer a supported GPU architecture: [http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list](http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list)

**Comment by honnibal** [comment]
Your change will break CUDA 8 though, which I think more people will have installed. We need some way of detecting the version, so we can set the correct architecture. 

The current workaround is to set `CUDA9=1` as an environment variable.

**Comment by christophfink** [comment]
`sm_20`was already listed as deprecated in 8.0, and `sm_30` should (!) work 
(cf. [http://web.archive.org/web/20170709180333/http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list](http://web.archive.org/web/20170709180333/http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list) – lacking a CUDA 8 installation to test it on, I assumed it would work.

Thanks for the workaround!

**Comment by honnibal** [comment]
Should now be fixed in v6.10.1
