### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [explosion/thinc#446]
**Summary**
Installing thinc on aarch64 via pip using command "pip3 install thinc" tries to build wheel from source code

**Problem description**
thinc doesn't have wheel for aarch64 on PyPI repository. So, while installing thinc via pip on aarch64, pip builds wheel for same resulting in it takes more time to install thinc. Making wheel available for aarch64 will benefit aarch64 users by minimizing thinc installation time.

**Expected Output**
Pip should be able to download thinc wheel from PyPI repository rather than building it from source code.

@thinc-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make thinc wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by honnibal** [comment]
We're working on wheel support for more platforms. It's a matter of build automation, so it's not something that's easy for others to assist with.

Please do not open template issues on multiple repositories. It is not appreciated.

**Comment by diegorusso** [comment]
Just want to resurrect this. Github now offers Arm runner for linux and Windows. Maybe it's time to reconsider this?
