### ISSUE TITLE
Add a CITATION

### ISSUE THREAD

**Issue by w4nderlust** [explosion/thinc#455]
Please add a CITATION like for spaCy https://github.com/explosion/spaCy/blob/master/CITATION so that people know how to cite Thinc :)

**Comment by waffles0W0** [comment]
do you know how to cite Thinc now :0

**Comment by danieldk** [comment]
Thanks reporting this issue! Thinc has a citation file now:

https://github.com/explosion/thinc/blob/master/CITATION.cff
