### ISSUE TITLE
ExtractWindow for nW > 1 gives wrong output ?

### ISSUE THREAD

**Issue by chiragjn** [explosion/thinc#47]
On thinc==6.10.1,

```python
data = [[1], [2], [3]]
d = np.array(data, dtype=np.float32)
e = ExtractWindow(nW=1)
print e(d)
```

which gives correct output as expected

```
array([[ 0.,  1.,  2.],
       [ 1.,  2.,  3.],
       [ 2.,  3.,  0.]], dtype=float32)
```

But 
```python
data = [[1], [2], [3]]
d = np.array(data, dtype=np.float32)
e = ExtractWindow(nW=2)
print e(d)
```

outputs

```
array([[ 0.,  0.,  1.,  2.,  3.],
       [ 1.,  2.,  2.,  3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)
```

If I understood the purpose of the method - concat by sliding a window, shouldn't this be

```
array([[ 0.,  0.,  1.,  2.,  3.],
       [ 0.,  1.,  2.,  3.,  0.],
       [ 1.,  2.,  3.,  0.,  0.]], dtype=float32)
```

**Comment by honnibal** [comment]
Definitely looks wrong --- thanks!

The problem will almost surely be in the `NumpyOps.seq2col` and `CupyOps.seq2col` methods.

**Comment by bastia1989** [comment]
I just tried, it seems the bug stll exists in 7.0.8 version. I think this might hinder users customize their own models
