### ISSUE TITLE
ImportError: No module named 'thinc.neural.gpu_ops'

### ISSUE THREAD

**Issue by Hisham-Hussein** [explosion/thinc#50]
Hi there and thanks for the excellent library. 

I have followed the steps [here](https://github.com/explosion/thinc) and even checked the 'cupy' and chainer are installed by running:
`python -c "import cupy; assert cupy"`

and then installed thinc successfully.

and then when I write:
`python -c "import thinc.neural.gpu_ops"`

i get the following error:
`ImportError: No module named 'thinc.neural.gpu_ops'`

```
[tfdeeplearning] D:\Data Science>conda --version
conda 4.0.8

[tfdeeplearning] D:\Data Science>python --version
Python 3.5.4

[tfdeeplearning] D:\Data Science>python -c "import spacy; print(spacy.__version__)"
2.0.4
```
I also added cuda-8 to my path

**Comment by honnibal** [comment]
Finally managed to improve this in 6.11.2:

* Now smarter about finding the path automatically (at least looks in the default place)
* You can now specify GPU usage as an "extra", so you can depend on `thinc[cuda]`. Usefully, you can do `thinc[cuda90]`, `thinc[cuda91]` or `thinc[cuda80]` to install the appropriate cupy wheel.
