### ISSUE TITLE
Mypy plugin crash analyzing `concatenate` called with `*args`

### ISSUE THREAD

**Issue by connorbrinton** [explosion/thinc#519]
While working on [some changes to SpaCy's type signatures](https://github.com/explosion/spaCy/pull/8773), I noticed that running Mypy on the SpaCy code base produces the following error:

```python
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3911, in accept
  File "mypy/nodes.py", line 1558, in accept
  File "mypy/checkexpr.py", line 271, in visit_call_expr
  File "mypy/checkexpr.py", line 353, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 858, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 917, in check_call
  File "mypy/checkexpr.py", line 1029, in check_callable_call
  File "mypy/checkexpr.py", line 729, in apply_function_plugin
  File ".../spaCy/.env/lib/python3.9/site-packages/thinc/mypy.py", line 31, in function_hook
    return get_reducers_type(ctx)
  File ".../spaCy/.env/lib/python3.9/site-packages/thinc/mypy.py", line 81, in get_reducers_type
    ctx.default_return_type.type, [arg_types[0].args[0], arg_types[0].args[1]]
IndexError: tuple index out of range
```

Based on some pdb debugging (using `mypy --pdb`) and reading the Thinc Mypy plugin code, I was able to come up with this minimal test case:

```
from thinc.api import chain, concatenate, Relu, Softmax

n_hidden = 32
dropout = 0.2

model1 = chain(
    Relu(nO=n_hidden, dropout=dropout),
    Relu(nO=n_hidden, dropout=dropout),
    Softmax()
)

model2 = chain(
    Relu(nO=n_hidden, dropout=dropout),
    Relu(nO=n_hidden, dropout=dropout),
    Softmax()
)

model3 = concatenate(*[model1, model2])
```

In this example, the use of variadic arguments (`*args`) is necessary for the error to occur.

I researched Mypy's typing system and looked into the Mypy plugin code, but wasn't able to figure out what the expected behavior would be here. The root problem is that [these lines](https://github.com/explosion/thinc/blob/a125b8cf6a518bf61a418dbd077d8849e8c30167/thinc/mypy.py#L53-L56), which build the `arg_types` list, result in only a single entry in `arg_types`:

```python
[builtins.list[thinc.model.Model*[thinc.types.Floats2d, thinc.types.Floats2d]]]
```

This is because the `get_reducers_type` function doesn't take into consideration the value of `ctx.arg_kinds`:

```python
(Pdb) p ctx
FunctionContext(..., arg_kinds=[[2]], ...)
```

(based on [this lookup table](https://github.com/python/mypy/blob/9f409c3d89c7fa65eff8cf67883473487e6effd4/mypy/nodes.py#L1525-L1537), 2 means `ArgKind.ARG_STAR`)

At this point I've probably researched the issue enough to fix it myself :joy: My proposal for how to fix this is to expand variadic arguments into two "fake arguments" during type-checking (in `get_reducers_type`). This would be an approximation of all of the possible inputs for the function, so it may not be totally sound, but might be better than the current crash?

Alternatively, this could be detected as a special-case and `Model[Any]` could be returned (or some generic indicator like that) 🙂

Thanks for making thinc! 😄

**Comment by svlandeg** [comment]
Oh wow, nice digging! 🤩 

Your solution sounds reasonable to me, but I definitely don't know all the `mypy` ins and outs. Would love to hear what others think. 

If it's not too much additional trouble, would you be able to create the `thinc` PR? (just refer to this issue with the full explanation, ofcourse)

**Comment by connorbrinton** [comment]
I went a little bit overboard making changes to the plugin and learned a ton in the process 🙂 I've gotten to the point where I think there should be some discussion on certain heuristics used by the original plugin. It may make sense for me to rescope my changes to not be quite so drastic 😅

Most of what I learned is summarized in [this commit](https://github.com/explosion/thinc/commit/22a8afa8e1b30eb32827927f81b32cf88e5f33bb), which annotates the Mypy plugin with numerous comments describing the functionality of each section. One of the more interesting things that I learned is the `ctx.args`, `ctx.arg_types` and `ctx.arg_kinds` attributes are lists of lists, with each outer element representing a single formal argument (function definition parameter) and each inner element representing a passed argument that *may* fill that formal argument slot.

As a concrete example, `range` has three formal arguments: `start`, `stop` and `step`. If `range` is called as `range(*args)`, `args` may fill the `start`, `stop` or `step` formal arguments, depending on the length of the list. If there is ambiguity in which actual argument may fill a particular formal argument slot, multiple actual arguments may be listed for each formal argument. For example, in the function call `range(*args, num)`, `num` may fill the `start`, `end` or `step` formal arguments depending on the length of `args`, so `ctx.args` would be something like `[[<*args>, <num>], [<*args>, <num>], [<*args>, <num>]]`.

The original Thinc Mypy plugin code doesn't actually make this distinction and instead takes the entire `ctx.args` list and applies `itertools.chain(*ctx.args)` to get the argument ordering. This approach only really makes sense when there's only a single _actual_ argument for each _formal_ argument. In other words, there's an unambiguous relationship between function call arguments and function definition parameters that can be determined statically.

One simple way to handle this distinction would be to have the Thinc Mypy plugin only handle cases where each formal argument can be statically determined to be filled by at most one actual argument not used for any other formal argument. This would limit the plugin's ability to infer model types under more complex calling scenarios (for example, with variadic arguments), but would at least help to avoid the crash that currently occurs when variadic arguments are passed.

The more complex way to handle this distinction would be combine information about the ordering of the actual and formal arguments to appropriately infer model types. This is challenging, because it requires reasoning both about the function *call* and the function *definition*. For example, the plugin would need to handle all of the following scenarios appropriately:
```python
chain(model_a, model_b, model_c)
chain(layer2=model_b, layer1=model_a)
chain(model_a, *[model_b], model_c)
```

In all of these scenarios, `chain` receives models A, B and C in the order `model_a < model_b < model_c`, and it's _possible_ to statically infer this fact. However, it seems fairly difficult to accomplish in practice, since Mypy only provides argument ordering information for actual and formal arguments separately, not together. In other words, there's no way (that I'm aware of) for Mypy to tell us that `model_b` will always precede `model_c` in the function call `chain(model_a, *[model_b], model_c)`.

I'm going to modify my code to only handle the simple approach to dealing with this ambiguity, since I think that will be a good step forward to not crash on variadic arguments. Down the road, perhaps once Mypy has helpers for determining argument ordering or someone thinks of a good way to determine argument ordering from the information provided by Mypy, this can be revisited 🙂

**Comment by honnibal** [comment]
Hi @connorbrinton ,

Thanks for the detailed digging, and sorry for the delay getting back to you on it!

This bit of code is quite tricky, and it turned out to be at the limit of what we could easily achieve with mypy.

To recap, the model types in chain have the following relationship to each other:

```
chain(Model[ArgA, ArgB], Model[ArgB, ArgC], Model[ArgC, ArgD], ..., Model[ArgY, ArgZ]) -> Model[ArgA, ArgZ]:
```

In other words, we need the output type of the first model to bind to the input type of the second model, and so on for all of the other models in the variadic args. 

The tricky thing is that there can be other types of relationships as well. For instance, you can have a combinator that groups the outputs of the models into a tuple. This will have a signature where all of the submodels have the same input type, but the output types can vary arbitrarily --- and then the output of the final model will be a tuple consisting of those arbitrary values.

This all looks to match the understanding in the comments you've added, so I'm sure we're on the same page :)

I don't think I fully follow your sketch of a solution though? If what you're saying is that mypy expects the variadic arguments to match in type, well, then yes we'll have a problem that we can't express that the members of the varargs in Thinc have a certain internal structure. We've hacked around it a bit with a plugin, but I must admit I never really understood how the plugin works.
