### ISSUE TITLE
Cupy TypeError when using asarray with torch tensors

### ISSUE THREAD

**Issue by marifdemirtas** [explosion/thinc#564]
Hi,

I'm chaining a custom feature extraction model with a PyTorchWrapper model. In the feature extraction part, I'm using asarray function on a torch tensor but as you can see below, cupy raises an error when MemoryPointer is called. Do you have any idea why that line raises an exception?

Thanks,

```
Traceback (most recent call last): 
...
  File "/storage/myuser/myproject/main.py", line 180, in forward
    features.append(model.ops.asarray2f(attrs, dtype="float32"))
  File "/storage/miniconda/envs/safirx-ml/lib/python3.9/site-packages/thinc/backends/ops.py", line 494, in asarray2f
    return cast(Floats2d, self.asarray(data, dtype=dtype))
  File "/storage/miniconda/envs/safirx-ml/lib/python3.9/site-packages/thinc/backends/cupy_ops.py", line 67, in asarray
    pointer = cupy.cuda.MemoryPointer(data.data_ptr())
  File "cupy/cuda/memory.pyx", line 343, in cupy.cuda.memory.MemoryPointer.__init__
TypeError: __init__() takes exactly 2 positional arguments (1 given)```

**Comment by adrianeboyd** [comment]
Hmm, this looks like a bug since from the cupy docs/code it looks like it should be `MemoryPointer(ptr, offset)`. I haven't tested it, but I suspect it should just be `cupy.cuda.MemoryPointer(data.data_ptr(), 0)`?

**Comment by marifdemirtas** [comment]
> Hmm, this looks like a bug since from the cupy docs/code it looks like it should be `MemoryPointer(ptr, offset)`. I haven't tested it, but I suspect it should just be `cupy.cuda.MemoryPointer(data.data_ptr(), 0)`?

I tried this but I got another TypeError, as the first argument of MemoryPointer is expected to be cupy.cuda.memory.BaseMemory but data.data_ptr() returns int.

**Comment by adrianeboyd** [comment]
Hmm, this is possibly all just relatively untested. We will look into it!
