### ISSUE TITLE
Compatibility problem with murmurhash <1.0.2

### ISSUE THREAD

**Issue by leodacyber** [explosion/thinc#592]
There is a compatibility issue using thinc with murmurhash <1.0.2. The necessary imports were introduced with version 1.0.2.

```File "/usr/lib/python3/dist-packages/thinc/layers/__init__.py", line 56, in <module>
   from .strings2arrays import strings2arrays
 File "/usr/lib/python3/dist-packages/thinc/layers/strings2arrays.py", line 2, in <module>
   from murmurhash import hash_unicode
ImportError: cannot import name 'hash_unicode' from 'murmurhash' (/usr/lib/python3/dist-packages/murmurhash/__init__.py)
```
From my point of view murmurhash should be pinned to >= 1.0.2 in the requirements.txt

Tested with versions:
thinc: 8.0.13
murmurhash: 1.0.1-2

**Comment by adrianeboyd** [comment]
That's a good point, thanks for the report!
