### ISSUE TITLE
upgrade typing_extensions version requirement

### ISSUE THREAD

**Issue by mayk0gan** [explosion/thinc#665]
Taken from `requirements.txt`: `typing_extensions>=3.7.4.1,<4.0.0.0; python_version < "3.8"`.

This requirement doesn't allow us to use this project in our codebase as many packages already upgraded the requirement of this package to version `>4.0.0` (`botocore-stubs`, `aioitertools`, and so on).
It also requires from `spaCy` for example to use the same requirement.

Is there any plan to upgrade it?

**Comment by adrianeboyd** [comment]
We still have to do some more testing to be sure, but it looks like we should be able extend this to `<4.2.0`.

**Comment by adrianeboyd** [comment]
This was addressed in v8.0.17.
