### ISSUE TITLE
GLIBCXX_3.4.21 (/lib64/libstdc++.so.6.0.21) dependecy not satisfiable on CentOS

### ISSUE THREAD

**Issue by aourednik** [explosion/thinc#68]
Thinc 6.10.2 triggers an error when running on Linux CentOS 7.5.x (latest). Called from SpaCy called from Rasa_nlu

It misses GLIBCXX_3.4.21 available in libstdc++.so.6.0.21 (64bit) but libstdc++.so.6.0.21 is not available (yet!) for CentOS. Could dependency be "lowered" to GLIBCXX_3.4.19 ?

```
File "/home/user/miniconda3/lib/python3.6/site-packages/spacy/language.py", line 18, in <module>
    from .pipeline import DependencyParser, Tensorizer, Tagger, EntityRecognizer
  File "pipeline.pyx", line 1, in init spacy.pipeline
  File "arc_eager.pxd", line 12, in init spacy.syntax.nn_parser
  File "search.pxd", line 35, in init spacy.syntax.arc_eager
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/user/miniconda3/lib/python3.6/site-packages/thinc/extra/search.cpython-36m-x86_64-linux-gnu.so)
```
Connected to [this issue](https://github.com/RasaHQ/rasa_nlu/issues/1210)

**Comment by honnibal** [comment]
We can try that, thanks for the report, and sorry for the inconvenience!

**Comment by honnibal** [comment]
I believe this should be fixed now.
