### ISSUE TITLE
Extracting / gathering / slicing vectors of a sequence

### ISSUE THREAD

**Issue by tokestermw** [explosion/thinc#70]
I'd like to get the last (and first) vector of a sequence. Would it be possible in the current `thinc` API?

It could look something like:

```
model = (
    tok2vec  # shape [batch_size, sequence_length, hidden_size]
    >> gather(-1)  # shape [batch_size, 1, hidden_size]
    >> softmax  # shape [batch_size, 1, output_size]
)
```

**Comment by honnibal** [comment]
Sure, that function should be easy to write. Note that we don't normally pass around vectors of shape `(batch_size, sequence_length, hidden_size)` for sequences though, unlike PyTorch etc. We usually have two formats:

* Flattened: This is a tuple of arrays `(data, lengths)`, where `data` is the concatenated array data, optionally with padding inserted, and `lengths` is an array of the sequence length integers.

* Unflattened: A list of arrays.

If you have unflattened data, your `gather` function should be easy to write. Something like this:

```python

from thinc.api import layerize
from thinc.neural.util import get_array_module

def gather(i):
    def gather_forward(seqs, drop=0.):
        picked = [seq[i] for i in seqs]
        # Get the shapes. We want to refer to these in the backward pass,
        # but we don't want to reference the seqs variable, or we won't be able
        # to free it until the backward pass is complete.
        shapes = [seq.shape for seq in seqs]
        def gather_backward(d_picked, sgd=None):
            d_seqs = []
            for shape, d_pick in zip(seqsd_picked:
                xp = get_array_module(d_pick)
                d_seq = xp.zeros(shape, dtype=d_pick.dtype)
                d_seq[i] = d_pick
                d_seqs.append(d_seq)
            return d_seqs
        return picked, gather_backward
    return layerize(gather_forward)
```
