### ISSUE TITLE
Pickling Error w/ Nested Function in with_flatten

### ISSUE THREAD

**Issue by millertracy** [explosion/thinc#73]
SpaCy: 2.0.12
thinc: 6.11.2
joblib: 0.11

   I'm trying to run the spaCy multi_processing.py example. I was getting a similar error as in issue #53 when i was using an older version of thinc - 6.10.3 and the same spaCy and joblib versions. After updating to 6.11.2, that issue was resolved but a new pickling error occurred. This new error is the following:

`AttributeError: Can't pickle local object 'with_flatten.<locals>.begin_update'`

Any updates to workaround this error?

**Comment by bestan** [comment]
Experiencing the same issues both on thinc 6.11.1 and 6.11.2
