### ISSUE TITLE
cupy arrays are not fully compatible with thinc, hindering GPU support

### ISSUE THREAD

**Issue by cmckain** [explosion/thinc#74]
Branching off of my comments on spacy bug [spacy#1798](https://github.com/explosion/spaCy/issues/1798#issuecomment-416026767), it would appear that cupy arrays, used in the course of using the GPU, are different enough (see [cupy#589](https://github.com/cupy/cupy/issues/589)) from numpy arrays as to prevent several portions of thinc from working. Case in point:
```python
def begin_update(self, keys_values_lengths, drop=0.):
        cdef uint64_t[::1] keys <-
        cdef long[::1] lengths
        cdef float[::1] values
        keys, values_, lengths = keys_values_lengths <-
```
This fails because cupy arrays do not support the implicit conversion that I think has to happen here for this to work. When I force the function that calls that to pass a numpy array, it works but it reveals a deadly mixing of numpy and cupy arrays around thinc. How does one get GPU support without cupy causing these problems?
ubuntu 18.04
python 3.6.5
spacy 2.0.12
thinc 6.10.3
cuda 9.2
cupy 4.4.0

**Comment by honnibal** [comment]
Should be fixed now.
