### ISSUE TITLE
Allow Pydantic >= 1.10

### ISSUE THREAD

**Issue by phillipuniverse** [explosion/thinc#778]
Hello, there is a hard dependency on Pydantic < 1.10. I would really like to use Pydantic 1.10 with Spacy but am unable to because of this requirement:

https://github.com/explosion/thinc/blob/1eaeb2bcabe9feb3153b829950ac05eb13bc818e/setup.cfg#L52

This was recently discussed at #744 and I guess there is a requirement to drop Python 3.6 in order to consume this upgrade? Just wondering if there is a timeline here for that or what the strategy is.

Thanks!

**Comment by svlandeg** [comment]
Hi! We should be able to support both Python 3.6 as well as Pydantic 1.10 - cf #779

**Comment by phillipuniverse** [comment]
Thanks @svlandeg!
