### ISSUE TITLE
Is there a way to check if `prefer_gpu` has been called?

### ISSUE THREAD

**Issue by nikita-galileo** [explosion/thinc#788]
Trying to understand how we might know if a user using spacy has called `spacy.prefer_gpu` yet. Looking through the thinc code it seems like I could almost check the value of some variable, but I'm not sure.

**Comment by polm** [comment]
Duplicate of https://github.com/explosion/spaCy/discussions/11648. Please don't ask the same question in multiple places; we'll follow up in the Discussion.
