### ISSUE TITLE
Does thinc support using multiple GPUs for a process?

### ISSUE THREAD

**Issue by soumyagk** [explosion/thinc#80]
I installed `thinc[cuda]` on my GPU machine that has 2 GPUs. After loading the spacy model with `spacy.prefer_gpu()`, I see about 35-56% GPU utilization on device 0. Also feeding in text >~3000 sentences threw `OutOfMemoryError`. Is there an API to utilize multiple GPUs if available, which can help with the memory errors?

**Comment by honnibal** [comment]
There's currently no way to use multiple GPUs, no. At the moment in spaCy we can't really saturate one GPU effectively, so I've assumed using multiple GPUs wouldn't help very much. How much memory does your card have, and which model are you training?

**Comment by soumyagk** [comment]
I'm using the GeForce GTX 1080 - so around 8GB memory. I get the OutOfMemoryErrors when I use the nlp model `en_core_web_sm` to parse text (346 KB file), when no other process is utilizing the GPU. I think putting a cap on how much text is passed in at once should avoid the memory errors.
