### ISSUE TITLE
Is there anyway to load a variable in a config file as a list?

### ISSUE THREAD

**Issue by sizhky** [explosion/thinc#883]
I'm training a huggingface code but this is a generic query

```
[TrainingConfig]
learning_rate=3e-5
max_steps=50
output_dir="./results",
per_device_train_batch_size=64
per_device_eval_batch_size=${per_device_train_batch_size}
evaluation_strategy="steps"
eval_steps=10
logging_strategy=${evaluation_strategy}
logging_steps=${eval_steps}
save_strategy=${evaluation_strategy}
save_steps=${eval_steps}
save_total_limit=1
seed=${ModelConfig.seed}
label_names=['x']
```

The label_names at the bottom is being parsed as a string "['x']" is there a way to read it as a list when parsing?

**Comment by rmitsch** [comment]
Hi @sizhky, try `label_names=["x"]` instead (" instead of ').

**Comment by sizhky** [comment]
Yes, this works. Thank you. Is there any page in documentation that describes this? 

You can point me to what could be the best place to add this in docs otherwise.

Another parallel request - Is there a way to add multiline strings in the file? This will be best useful for comments/descriptions/changelog type of fields

**Comment by rmitsch** [comment]
> Yes, this works. Thank you. Is there any page in documentation that describes this?
> 
> You can point me to what could be the best place to add this in docs otherwise.

This is not in the docs, AFAIK. Towards the end of the [usage section](https://github.com/explosion/confection#-usage) would probably be a good idea. Happy to look at the PR if you want to do this!

> Another parallel request - Is there a way to add multiline strings in the file? This will be best useful for comments/descriptions/changelog type of fields

Yes, like this:
```cfg
[TrainingConfig]
label_names=["x"]
test = """
    this is a
    test"""
```
The resulting dict is `{'TrainingConfig': {'label_names': ['x'], 'test': '"""\nthis is a\ntest"""'}}`. In general we are congruent with the CFG format.
