### ISSUE TITLE
thinc/examples/spacy_tagger.py

### ISSUE THREAD

**Issue by d5555** [explosion/thinc#90]
Hello 
Could you help to run this example please?   thinc/examples/spacy_tagger.py

I got Error : ModuleNotFoundError: No module named 'thinc.neural._classes.spacy_vectors'

Looks like there is no module spacy_vectors

**Comment by honnibal** [comment]
Sorry for not getting back to you on this, but the previous versions of Thinc were mostly for internal spaCy use. We're close to releasing a new version, where things will be much more reliable and fully documented.
