### ISSUE TITLE
Runtime errors in glove_mwe_multipool_predict.py

### ISSUE THREAD

**Issue by cbader** [explosion/thinc#91]
I finally got glove_mwe_multipool_predict.py to run after some editing of imports, urls, etc., but now I'm getting runtime errors.

python examples/text-pair/glove_mwe_multipool_predict.py
{'quiet': False, 'out_loc': None, 'use_gpu': False, 'pieces': 3, 'nb_epoch': 20, 'pooling': 'mean+max', 'dropout_decay': 0.0, 'dropout': 0.0, 'max_batch_size': 128, 'min_batch_size': 1, 'depth': 2, 'width': 64, 'dataset': 'quora'}
Load spaCy
Construct model
/home/AI_a628600/anaconda3/lib/python3.6/site-packages/thinc/extra/load_nlp.py:25: RuntimeWarning: invalid value encountered in true_divide
  vectors[lex.rank] = lex.vector / lex.vector_norm
Read and parse data: quora
Initialize with data (LSUV)
(40429, 2)
/home/AI_a628600/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Accuracy before training 0.6343218976477281
Train
  0%|                                                      | 0/363859 [00:00<?, ?it/s]examples/text-pair/glove_mwe_multipool_predict.py:198: RuntimeWarning: invalid value encountered in greater_equal
  assert (yh >= 0.0).all()
Traceback (most recent call last):
  File "examples/text-pair/glove_mwe_multipool_predict.py", line 216, in <module>
    plac.call(main)
  File "/home/AI_a628600/anaconda3/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/AI_a628600/anaconda3/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "examples/text-pair/glove_mwe_multipool_predict.py", line 198, in main
    assert (yh >= 0.0).all()
AssertionError

Any ideas?  Should I just remove the assert?

CB

**Comment by honnibal** [comment]
Sorry for not getting back to you on this, but the previous versions of Thinc were mostly for internal spaCy use. We're close to releasing a new version, where things will be much more reliable and fully documented.
