### ISSUE TITLE
ONNX Support

### ISSUE THREAD

**Issue by ayaz-amin** [explosion/thinc#94]
I was wondering if Open Neural Network Exchange (ONNX) support will be available (sometime) in the future. With ONNX, neural network models can be transferred from one deep-learning library to another. It would be great if there was an importer that can import ONNX models. That way, a model does not need to be re-written in Thinc.

**Comment by honnibal** [comment]
I'd welcome work on this, but it'll only be available for a subset of architectures, as Thinc will make it easy to write models that can't be converted to ONNX. As soon as we use a non-standard layer type, the network won't be convertible.

**Comment by honnibal** [comment]
I'm going to close this, as it will definitely be better to use a wrapper.
