### ISSUE TITLE
Non-x86 support

### ISSUE THREAD

**Issue by edelsohn** [explosion/thinc#95]
thinc/include/openblas_config.h defines numerous x86-specific macros but the framework itself seems portable.

**Comment by honnibal** [comment]
Ah that needs to be removed --- it's no longer used. That was part of an abandoned attempt to use the OpenBLAS kernels. We're now using the Blis kernels, via our package [cython-blis](https://github.com/explosion/cython-blis).

We can support any architecture Blis supports, but there may be some build steps we have to perform to make that happen.

**Comment by edelsohn** [comment]
Why not be portable with respect to BLAS libraries?

**Comment by honnibal** [comment]
@edelsohn We had a lot of trouble with variation in underlying BLAS engines in spaCy, so when we put in Blis we left it fixed. But it's true that it's a bit limiting.

The next version of Thinc will be more general, and support non-spaCy use-cases as well. We've therefore set a default of using numpy for matrix multiplication, with an option for Blis. This will take care of the problem.

I'm sorry if it's been frustrating that this has taken so long to be resolved. We're really pleased with the new version though, it makes a lot of things much easier.
