### ISSUE TITLE
Running glove_mwe_multipool_siamese.py

### ISSUE THREAD

**Issue by OlhaOlha** [explosion/thinc#99]
Hi @ines and @honnibal 
Thank you for your work!

I ran your script glove_mwe_multipool_siamese.py
The only things that I had to change were:
1. the link to quora source file in thinc/extra/datasets.py
QUORA_QUESTIONS_URL = "http://qim.fs.quoracdn.net/quora_duplicate_questions.tsv" (instead of "http://qim.ec.quoracdn.net/quora_duplicate_questions.tsv")

2. I changed "en" to "en_vectors_web_lg" to solve ValueError:
Cannot create vectors table with dimension 0.
If you're using pre-trained vectors, are the vectors loaded?

nlp = get_spacy("en") -> nlp = get_spacy("en_vectors_web_lg")

I've got near 0.8 f1-score with my data.

My question is why did you write this line?
Warning: The code here might be broken --- the results don't seem right
What exactly might be wrong?

Thank you in advance!

**Comment by honnibal** [comment]
It's just that that score is fairly low for that dataset. I've never been certain it was doing what it was supposed to, so I added the note. Sorry for the delay seeing this!
